### ISSUE TITLE
env property does not visible in child if we use env as plugin in parent

### ISSUE THREAD

**Issue by Preeternal** [yolk-oss/elysia-env#1]
env property does not visible in child if we use env as plugin in parent

**Comment by fecony** [comment]
Hey @Preeternal That's common limitation from Elysia, type inference is lost if you don't chain methods

```ts
new Elysia()
    .use(env({ IS_ENABLED: t.Boolean({ default: false }) }))
    .get('/', ({ env }) => env)  // is here because 'use` and 'get' are chained, type is infered
    .listen(4242, ({ hostname, port }) => {
        console.log(`🦊 📂 - Listening on http://${hostname}:${port}`)
    })
```

```ts
const app = new Elysia().use(env({ IS_ENABLED: t.Boolean({ default: false }) }));

app
    .get('/', ({ env }) => env)  // is NOT "here" because 'use` and 'get' are NOT chained, type is lost
    .listen(4242, ({ hostname, port }) => {
        console.log(`🦊 📂 - Listening on http://${hostname}:${port}`)
    })
```

What you can do is just use plugin in every child as it does not do much and should add env variables only once and not on each request since it uses a `decorate`

or as some developers did create `setup` file that has all the things that you need in your app(jwt, some state, plugins) and `.use(setup)` it in child/handlers/whatever where you need access to setup stuff

If you need more help feel free to ask questions in Elysia Discord 🦊
